### ISSUE TITLE
Cannot download module

### ISSUE THREAD

**Issue by renard** [blacknon/go-sshlib#9]
go-sshlib cannot be downloaded because `p11.Module` uses undefined `Destroy` function:

```shell
 go get -v  github.com/blacknon/go-sshlib
github.com/blacknon/go-sshlib
# github.com/blacknon/go-sshlib
go/pkg/mod/github.com/blacknon/go-sshlib@v0.1.3/auth.go:220:8: module.Destroy undefined (type p11.Module has no field or method Destroy)
```

```shell
go version
go version go1.16 darwin/amd64
```

**Comment by blacknon** [comment]
I'm replacing the library I'm using (github.com/miekg/pkcs11) because the pull request hasn't passed yet, but it doesn't seem to work.

Please install with the following command.

`` `bash
mkdir -p $ GOPATH / src / github.com/blacknon && cd $ _
git clone git@github.com:blacknon/go-sshlib.git
cd go-sshlib
go install
`` ```
